language: cpp

env:
  - QMAKESPEC=linux-g++
  - QMAKESPEC=linux-clang

install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551
  - sudo apt-get update -qq
  - sudo apt-get install qt55base qt55tools libboost-all-dev

script:
  - /opt/qt55/bin/qmake qt=qt5 -v
  - /opt/qt55/bin/qmake qt=qt5 IrcClient.pro
  - make
  
notifications:
  irc:  
    channels: "irc.oftc.net#genirc"
    skip_join: true
