language: cpp

install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt541
  - sudo apt-get update -qq
  - sudo apt-get install qt54base qt54tools libboost-all-dev

script:
  - /opt/qt54/bin/qmake qt=qt5 -v
  - /opt/qt54/bin/qmake qt=qt5 IrcClient.pro
  - make