install:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
    
    set QTDIR=C:\Qt\5.4\msvc2013_opengl
    
    set PATH=%PATH%;%QTDIR%\bin
    
build_script:
- cmd: >-
    qmake IrcClient.pro -spec win32-msvc2010 "INCLUDEPATH+=C:\Libraries\boost_1_59_0"
    
    nmake